#!/bin/sh -e

# this variable is only set if the usepeerdns pppd option is being used
[ "$USEPEERDNS" ] || exit 0

# create a lockfile so we are not run multiple times
if [ ! -e /tmp/ntp-ip-lock ]; then
  : > /tmp/ntp-ip-lock
else
    exit 0
fi

LIABNTP=`grep "liabNTP=" /tmp/optionsfile | cut -f2 -d"="`
if [ -n $LIABNTP ]; then
      # kill off ntpd and restart it
    killall -9 ntpd
    logger -i -s "Restarting ntpd"
    if /usr/sbin/ntpd -g -p /var/run/ntpd.pid; then
        logger -i -s "ntpd running"
    else
        logger -i -s "failed restarting ntpd"
    fi
fi

rm -f /tmp/ntp-ip-lock

exit 0

