all:
	$(MAKE) -C 	adc78h98
	$(MAKE) -C 	max1098
	$(MAKE) -C 	modem

clean:
	$(MAKE) -C 	adc78h98						clean
	$(MAKE) -C 	max1098							clean
	$(MAKE) -C 	modem							clean

distclean:
	$(MAKE) -C	adc78h98						distclean
	$(MAKE) -C	max1098							distclean
	$(MAKE) -C	modem							distclean



