#!/bin/sh
#

exec chat -E					\
    TIMEOUT  	5				\
    ECHO 		  ON				\
    ABORT		  '\nBUSY\r'			\
    ABORT		  '\nERROR\r'			\
    ABORT		  '\nNO ANSWER\r'			\
    ABORT		  '\nNO CARRIER\r'		\
    ABORT		  '\nNO DIALTONE\r'		\
    ABORT     '\nRINGING\r\n\r\nRINGING\r'	\
    '' ATZ \
    OK-AT-OK AT+CMEE=1 \
    OK-AT-OK AT+CGDCONT=1,\"IP\",\"internet\" \
    OK-AT-OK AT+CGQREQ=1,2,4,3,6,31 \
    OK-AT-OK AT+CGQMIN=1,2,4,3,6,31 \
    OK-AT-OK AT+CGATT=1 \
    OK-AT-OK AT+CGREG? \
    '+CGREG: 0,1'-AT+CGREG? -AT+CGREG? \
    '+CGREG: 0,1'-AT+CGREG? -AT+CGREG? \
    '+CGREG: 0,1' '' \
    OK-AT-OK ATD*99# \
    CONNECT ''
